/**
 * Design system reminder — 環境章節以墨綠與自然紙張為基底，將碳排放資料做成可逐步翻閱的技術年報。
 */
import { useMemo, useState as reactUseState, type Dispatch, type ReactNode, type SetStateAction } from "react";
import { flushSync } from "react-dom";
import { BarChart3, ChevronLeft, ChevronRight, Plus, Trash2 } from "lucide-react";
import { useLocation } from "wouter";
import { EsgLayout } from "@/components/EsgLayout";
import { TextField } from "@/components/FormPrimitives";
import { useSchoolProfile } from "@/contexts/SchoolProfileContext";
import { SubmissionActions } from "@/components/SubmissionActions";

type Stationary = { name: string; category: string; fuel: "towngas" | "lpg" | "diesel"; value: number };
type Mobile = { name: string; fuel: "petrol" | "diesel"; value: number };
type RefrigerantRow = { name: string; category: string; gwp: number; value: number };
type Power = { name: string; company: "clp" | "hke"; value: number };
type SimpleRecord = { name: string; value: number };

// 環境頁多個輸入欄位會在陣列更新器內讀取事件值。立即套用更新，確保事件
// 尚未完成派發前已取得數值，避免 React 將 currentTarget 重設為 null。
function useState<T>(initialValue: T) {
  const [value, setValue] = reactUseState(initialValue);
  const setValueImmediately: Dispatch<SetStateAction<T>> = (nextValue) => {
    flushSync(() => setValue(nextValue));
  };
  return [value, setValueImmediately] as const;
}

const refrigerants = [{ name: "R-410A", gwp: 1924 }, { name: "HFC-32 (R-32)", gwp: 677 }, { name: "HFC-134a", gwp: 1300 }, { name: "R-404A", gwp: 3943 }, { name: "R-407C", gwp: 1624 }, { name: "HFC-23", gwp: 12400 }, { name: "HFC-125", gwp: 3170 }, { name: "HFC-227ea", gwp: 3350 }, { name: "R-507 / R-507A", gwp: 3985 }, { name: "無補充／不適用", gwp: 0 }];
const tabs = [{ id: "scope1", label: "範疇一", sub: "直接排放" }, { id: "scope2", label: "範疇二", sub: "能源間接" }, { id: "scope3", label: "範疇三", sub: "其他間接" }, { id: "summary", label: "報告", sub: "總覽" }] as const;
type Tab = (typeof tabs)[number]["id"];

function UpdateButton({ onClick, label }: { onClick: () => void; label: string }) { return <button onClick={onClick} className="inline-flex items-center gap-1.5 border border-[#173D35] bg-[#173D35] px-3 py-2 text-xs font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#0F2D26] active:scale-[.97]"><Plus className="h-3.5 w-3.5" />{label}</button>; }
function DeleteButton({ onClick }: { onClick: () => void }) { return <button onClick={onClick} aria-label="刪除紀錄" className="grid h-9 w-9 place-items-center text-[#9A3E35] transition hover:bg-[#F5E6E1] active:scale-[.97]"><Trash2 className="h-4 w-4" /></button>; }
function RecordShell({ title, description, action, children }: { title: string; description: string; action: ReactNode; children: ReactNode }) { return <section className="border border-[#173D35]/12 bg-white p-5 shadow-[0_10px_30px_rgba(28,45,35,.055)] sm:p-6"><div className="mb-4 flex flex-wrap items-end justify-between gap-3 border-b border-[#173D35]/10 pb-4"><div><h2 className="font-serif text-xl font-bold text-[#1F2D26]">{title}</h2><p className="mt-1 text-xs leading-5 text-[#718078]">{description}</p></div>{action}</div>{children}</section>; }
function Metric({ label, value, unit, tone = "green" }: { label: string; value: string; unit: string; tone?: "green" | "blue" | "red" }) { const color = { green: "border-[#173D35] text-[#173D35]", blue: "border-[#273C73] text-[#273C73]", red: "border-[#9A3E35] text-[#9A3E35]" }[tone]; return <div className={`border-l-4 bg-white p-4 shadow-[0_8px_18px_rgba(28,45,35,.06)] ${color}`}><p className="text-[10px] font-bold tracking-[0.11em] text-[#718078]">{label}</p><p className="mt-2 font-serif text-3xl font-bold leading-none">{value}</p><p className="mt-1 text-[11px] font-semibold text-[#718078]">{unit}</p></div>; }

export default function Environment() {
  const [tab, setTab] = useState<Tab>("scope1");
  const [, setLocation] = useLocation();
  const { profile } = useSchoolProfile();
  const persons = Number.isFinite(profile.studentCount) ? profile.studentCount : 0;
  const area = Number.isFinite(profile.grossFloorArea) ? profile.grossFloorArea : 0;
  const [stationary, setStationary] = useState<Stationary[]>([{ name: "", category: "科學實驗室本生燈", fuel: "towngas", value: 0 }]);
  const [mobile, setMobile] = useState<Mobile[]>([{ name: "", fuel: "petrol", value: 0 }]);
  const [ac, setAc] = useState<RefrigerantRow[]>([{ name: "", category: "課室冷氣機", gwp: 1924, value: 0 }]);
  const [refrig, setRefrig] = useState<RefrigerantRow[]>([{ name: "", category: "教員室雪櫃", gwp: 1300, value: 0 }]);
  const [power, setPower] = useState<Power[]>([{ name: "", company: "clp", value: 0 }]);
  const [gas, setGas] = useState<SimpleRecord[]>([{ name: "", value: 0 }]);
  const [water, setWater] = useState<SimpleRecord[]>([{ name: "", value: 0 }]);
  const [sewage, setSewage] = useState<SimpleRecord[]>([{ name: "", value: 0 }]);
  const [paper, setPaper] = useState<SimpleRecord[]>([{ name: "", value: 0 }]);
  const total = useMemo(() => {
    const factor: Record<Stationary["fuel"], number> = { towngas: 2.5529, lpg: 3.0394, diesel: 2.6569 };
    const s1 = (stationary.reduce((sum, row) => sum + row.value * factor[row.fuel], 0) + mobile.reduce((sum, row) => sum + row.value * (row.fuel === "petrol" ? 2.6839 : 2.6722), 0) + ac.reduce((sum, row) => sum + row.value * row.gwp, 0) + refrig.reduce((sum, row) => sum + row.value * row.gwp, 0)) / 1000;
    const s2 = (power.reduce((sum, row) => sum + row.value * (row.company === "clp" ? 0.38 : 0.6), 0) + gas.reduce((sum, row) => sum + row.value * 0.548, 0)) / 1000;
    const s3 = (water.reduce((sum, row) => sum + row.value * 0.256, 0) + sewage.reduce((sum, row) => sum + row.value * 0.22, 0) + paper.reduce((sum, row) => sum + row.value * 3.72, 0)) / 1000;
    return { s1, s2, s3, grand: s1 + s2 + s3 };
  }, [stationary, mobile, ac, refrig, power, gas, water, sewage, paper]);
  const go = (direction: -1 | 1) => { const index = tabs.findIndex((item) => item.id === tab); setTab(tabs[Math.max(0, Math.min(tabs.length - 1, index + direction))].id); };
  return (
    <EsgLayout chapter="environment" eyebrow="環境與碳排放" title="環境與碳排放計算器" description="按三個排放範疇整理能源、設施與資源消耗，讓學校可由基線開始追蹤環境表現。" image="/manus-storage/esg-environment_bed8f622.jpg">
      <div className="mb-6 grid gap-px overflow-hidden border border-[#173D35]/15 bg-[#173D35]/15 sm:grid-cols-4">{tabs.map((item, index) => <button key={item.id} onClick={() => setTab(item.id)} className={`flex items-center gap-3 px-4 py-4 text-left transition ${tab === item.id ? "bg-[#173D35] text-white" : "bg-[#FCFBF7] text-[#43534A] hover:bg-white"}`}><span className="font-serif text-2xl font-bold opacity-75">0{index + 1}</span><span><strong className="block text-sm">{item.label}</strong><small className={`block text-[10px] font-bold tracking-[0.08em] ${tab === item.id ? "text-[#D9E4B9]" : "text-[#718078]"}`}>{item.sub}</small></span></button>)}</div>
      {tab === "scope1" && <div className="space-y-5">
        <RecordShell title="1.1 固定燃燒源" description="灰色範例僅供填寫參考，請按實際資料輸入。" action={<UpdateButton label="添加固定燃燒源" onClick={() => setStationary((rows) => [...rows, { name: "", category: "其他固定設施", fuel: "towngas", value: 0 }])} />}><div className="space-y-2">{stationary.map((row, index) => <div key={index} className="grid items-end gap-2 border border-[#173D35]/10 bg-[#FCFBF7] p-3 md:grid-cols-[1.2fr_1.2fr_1fr_.8fr_40px]"><TextField label="設施／場所名稱" value={row.name} placeholder="例如：化學實驗室" onChange={(v) => setStationary((rows) => rows.map((item, i) => i === index ? { ...item, name: v } : item))} /><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">預設類別</span><select value={row.category} onChange={(e) => setStationary((rows) => rows.map((item, i) => i === index ? { ...item, category: e.currentTarget.value } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm"><option>科學實驗室本生燈</option><option>家政室煮食爐</option><option>學校食堂／小賣部廚房</option><option>緊急發電機</option><option>其他固定設施</option></select></label><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">燃料類型</span><select value={row.fuel} onChange={(e) => setStationary((rows) => rows.map((item, i) => i === index ? { ...item, fuel: e.currentTarget.value as Stationary["fuel"] } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm"><option value="towngas">煤氣</option><option value="lpg">液化石油氣</option><option value="diesel">柴油</option></select></label><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">全年用量</span><input type="number" value={row.value} onChange={(e) => setStationary((rows) => rows.map((item, i) => i === index ? { ...item, value: Number(e.currentTarget.value) } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm" /></label><DeleteButton onClick={() => setStationary((rows) => rows.filter((_, i) => i !== index))} /></div>)}</div></RecordShell>
        <RecordShell title="1.2 流動燃燒源" description="灰色範例僅供填寫參考，請按實際資料輸入。" action={<UpdateButton label="添加學校車輛" onClick={() => setMobile((rows) => [...rows, { name: "", fuel: "petrol", value: 0 }])} />}><div className="space-y-2">{mobile.map((row, index) => <div key={index} className="grid items-end gap-2 border border-[#173D35]/10 bg-[#FCFBF7] p-3 md:grid-cols-[1.5fr_1fr_1fr_40px]"><TextField label="車輛名稱／描述" value={row.name} placeholder="例如：校巴" onChange={(v) => setMobile((rows) => rows.map((item, i) => i === index ? { ...item, name: v } : item))} /><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">燃料類型</span><select value={row.fuel} onChange={(e) => setMobile((rows) => rows.map((item, i) => i === index ? { ...item, fuel: e.currentTarget.value as Mobile["fuel"] } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm"><option value="petrol">無鉛汽油</option><option value="diesel">柴油</option></select></label><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">全年用量（L）</span><input type="number" value={row.value} onChange={(e) => setMobile((rows) => rows.map((item, i) => i === index ? { ...item, value: Number(e.currentTarget.value) } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm" /></label><DeleteButton onClick={() => setMobile((rows) => rows.filter((_, i) => i !== index))} /></div>)}</div></RecordShell>
        <RefrigerantRecords title="1.3 冷氣機設備" description="按本年補充雪種量計算設備逃逸性排放。" rows={ac} setRows={setAc} newCategory="課室冷氣機" actionLabel="添加冷氣機" placeholder="例如：1C班課室冷氣機" categories={["課室冷氣機", "教員室冷氣機", "禮堂冷氣機", "特別室冷氣機"]} />
        <RefrigerantRecords title="1.4 冷凍設施設備" description="包括雪櫃、冷藏櫃及其他冷凍設備。" rows={refrig} setRows={setRefrig} newCategory="教員室雪櫃" actionLabel="添加冷凍設施" placeholder="例如：化學實驗室冷凍櫃" categories={["教員室雪櫃", "家政室雪櫃", "小賣部雪櫃", "實驗室冷藏櫃"]} />
      </div>}
      {tab === "scope2" && <div className="space-y-5"><RecordShell title="2.1 外購電力消耗" description="灰色範例僅供填寫參考，請按實際資料輸入。" action={<UpdateButton label="添加電力紀錄" onClick={() => setPower((rows) => [...rows, { name: "", company: "clp", value: 0 }])} />}><div className="space-y-2">{power.map((row, index) => <div key={index} className="grid items-end gap-2 border border-[#173D35]/10 bg-[#FCFBF7] p-3 md:grid-cols-[1.5fr_1fr_1fr_40px]"><TextField label="紀錄名稱／電表" value={row.name} placeholder="例如：主校舍電表" onChange={(v) => setPower((rows) => rows.map((item, i) => i === index ? { ...item, name: v } : item))} /><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">電力公司</span><select value={row.company} onChange={(e) => setPower((rows) => rows.map((item, i) => i === index ? { ...item, company: e.currentTarget.value as Power["company"] } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm"><option value="clp">中華電力 CLP</option><option value="hke">香港電燈 HKE</option></select></label><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">用電量（kWh）</span><input type="number" value={row.value} onChange={(e) => setPower((rows) => rows.map((item, i) => i === index ? { ...item, value: Number(e.currentTarget.value) } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm" /></label><DeleteButton onClick={() => setPower((rows) => rows.filter((_, i) => i !== index))} /></div>)}</div></RecordShell><SimpleRecords title="2.2 外購管道煤氣消耗" description="灰色範例僅供填寫參考，請按實際資料輸入。" rows={gas} setRows={setGas} actionLabel="添加煤氣紀錄" placeholder="例如：全校煤氣表" unit="用煤氣量（單位）" /></div>}
      {tab === "scope3" && <div className="space-y-5"><SimpleRecords title="3.1 食水消耗" description="食水排放係數為 0.256 kg CO₂e／m³。" rows={water} setRows={setWater} actionLabel="添加食水紀錄" placeholder="例如：全校水表" unit="耗水量（m³）" /><SimpleRecords title="3.2 污水排放" description="污水排放係數為 0.220 kg CO₂e／m³。" rows={sewage} setRows={setSewage} actionLabel="添加污水紀錄" placeholder="例如：全校水表" unit="污水量（m³）" /><SimpleRecords title="3.3 廢紙棄置" description="廢紙排放係數為 3.720 kg CO₂e／kg。" rows={paper} setRows={setPaper} actionLabel="添加廢紙紀錄" placeholder="例如：辦公室行政廢紙" unit="廢紙重量（kg）" /></div>}
      {tab === "summary" && <div className="space-y-6"><section className="grid gap-4 md:grid-cols-3"><Metric label="溫室氣體淨排放總量" value={total.grand.toFixed(2)} unit="公噸 CO₂e ／年" /><Metric label="全校人均碳排放量" value={(total.grand / Math.max(1, persons)).toFixed(3)} unit="公噸 CO₂e ／人" tone="blue" /><Metric label="單位面積碳排放強度" value={(total.grand * 1000 / Math.max(1, area)).toFixed(2)} unit="kg CO₂e ／m²" tone="red" /></section><section className="border border-[#173D35]/12 bg-white p-5 shadow-[0_10px_30px_rgba(28,45,35,.055)] sm:p-6"><div className="flex items-center gap-2 border-b border-[#173D35]/10 pb-4"><BarChart3 className="h-5 w-5 text-[#173D35]" /><h2 className="font-serif text-xl font-bold">各範疇溫室氣體排放資料統計</h2></div><div className="mt-5 space-y-4">{([{ label: "Scope 1 直接排放", value: total.s1, color: "bg-[#173D35]" }, { label: "Scope 2 能源間接", value: total.s2, color: "bg-[#273C73]" }, { label: "Scope 3 其他間接", value: total.s3, color: "bg-[#9A3E35]" }] as const).map((row) => <div key={row.label}><div className="flex justify-between gap-4 text-sm"><span className="font-bold text-[#33443A]">{row.label}</span><span className="font-serif font-bold text-[#173D35]">{row.value.toFixed(3)} <small className="font-sans text-[10px] text-[#718078]">t CO₂e</small></span></div><div className="mt-2 h-2 overflow-hidden bg-[#EEF0EA]"><div className={`h-full ${row.color}`} style={{ width: `${total.grand ? row.value / total.grand * 100 : 0}%` }} /></div><p className="mt-1 text-right text-[10px] font-bold tracking-[0.08em] text-[#718078]">{total.grand ? (row.value / total.grand * 100).toFixed(1) : 0}%</p></div>)}</div></section></div>}
      <SubmissionActions section="environment" data={{ stationary, mobile, ac, refrig, power, gas, water, sewage, paper, total }} />
      <div className="mt-6 flex items-center justify-between gap-3">{tab === "summary" ? <button onClick={() => go(-1)} className="inline-flex items-center gap-2 border border-[#173D35]/25 bg-white px-4 py-2.5 text-xs font-bold text-[#314039] transition hover:border-[#173D35]"><ChevronLeft className="h-4 w-4" />上一階段</button> : <button disabled={tab === "scope1"} onClick={() => go(-1)} className="inline-flex items-center gap-2 border border-[#173D35]/25 bg-white px-4 py-2.5 text-xs font-bold text-[#314039] transition hover:border-[#173D35] disabled:cursor-not-allowed disabled:opacity-35"><ChevronLeft className="h-4 w-4" />上一階段</button>}{tab === "summary" ? <button onClick={() => setLocation("/social")} className="inline-flex items-center gap-2 bg-[#173D35] px-4 py-2.5 text-xs font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#0F2D26] active:scale-[.97]">下一章<ChevronRight className="h-4 w-4" /></button> : <button onClick={() => go(1)} className="inline-flex items-center gap-2 bg-[#173D35] px-4 py-2.5 text-xs font-bold text-white transition hover:-translate-y-0.5 hover:bg-[#0F2D26] active:scale-[.97]">下一階段<ChevronRight className="h-4 w-4" /></button>}</div>
    </EsgLayout>
  );
}

function RefrigerantRecords({ title, description, rows, setRows, newCategory, actionLabel, placeholder, categories }: { title: string; description: string; rows: RefrigerantRow[]; setRows: Dispatch<SetStateAction<RefrigerantRow[]>>; newCategory: string; actionLabel: string; placeholder: string; categories: string[] }) { return <RecordShell title={title} description={description} action={<UpdateButton label={actionLabel} onClick={() => setRows((current) => [...current, { name: "", category: newCategory, gwp: 1924, value: 0 }])} />}><div className="space-y-2">{rows.map((row, index) => <div key={index} className="grid items-end gap-2 border border-[#173D35]/10 bg-[#FCFBF7] p-3 md:grid-cols-[1.2fr_1fr_1fr_.8fr_40px]"><TextField label="位置／名稱" value={row.name} placeholder={placeholder} onChange={(v) => setRows((items) => items.map((item, i) => i === index ? { ...item, name: v } : item))} /><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">類別</span><select value={row.category} onChange={(e) => setRows((items) => items.map((item, i) => i === index ? { ...item, category: e.currentTarget.value } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm">{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">雪種類型</span><select value={row.gwp} onChange={(e) => setRows((items) => items.map((item, i) => i === index ? { ...item, gwp: Number(e.currentTarget.value) } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm">{refrigerants.map((ref) => <option key={`${ref.name}-${ref.gwp}`} value={ref.gwp}>{ref.name} (GWP {ref.gwp})</option>)}</select></label><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">本年補充量（kg）</span><input type="number" value={row.value} onChange={(e) => setRows((items) => items.map((item, i) => i === index ? { ...item, value: Number(e.currentTarget.value) } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm" /></label><DeleteButton onClick={() => setRows((items) => items.filter((_, i) => i !== index))} /></div>)}</div></RecordShell>; }
function SimpleRecords({ title, description, rows, setRows, actionLabel, placeholder, unit }: { title: string; description: string; rows: SimpleRecord[]; setRows: Dispatch<SetStateAction<SimpleRecord[]>>; actionLabel: string; placeholder: string; unit: string }) { return <RecordShell title={title} description={description} action={<UpdateButton label={actionLabel} onClick={() => setRows((current) => [...current, { name: "", value: 0 }])} />}><div className="space-y-2">{rows.map((row, index) => <div key={index} className="grid items-end gap-2 border border-[#173D35]/10 bg-[#FCFBF7] p-3 md:grid-cols-[1.7fr_1fr_40px]"><TextField label="紀錄名稱" value={row.name} placeholder={placeholder} onChange={(v) => setRows((items) => items.map((item, i) => i === index ? { ...item, name: v } : item))} /><label><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">{unit}</span><input type="number" value={row.value} onChange={(e) => setRows((items) => items.map((item, i) => i === index ? { ...item, value: Number(e.currentTarget.value) } : item))} className="mt-1.5 w-full border border-[#173D35]/15 bg-white px-2 py-2.5 text-sm" /></label><DeleteButton onClick={() => setRows((items) => items.filter((_, i) => i !== index))} /></div>)}</div></RecordShell>; }
