/**
 * Design system reminder — 年報中的資料欄位應像附註式證據表：清楚單位、細線、暖白底與可掃讀的欄位分組。
 */
import type { ReactNode } from "react";
import { Check } from "lucide-react";

export function NumberField({ label, helper, value, onChange, min = 0, max, step = 1, suffix, placeholder }: { label: string; helper?: string; value: number; onChange: (value: number) => void; min?: number; max?: number; step?: number; suffix?: string; placeholder?: string }) {
  return <label className="block rounded-none border border-[#173D35]/10 bg-[#FCFBF7] p-3.5 transition focus-within:border-[#173D35]/45 focus-within:shadow-[0_0_0_3px_rgba(23,61,53,.08)]"><span className="block text-sm font-bold leading-5 text-[#27352E]">{label}</span>{helper && <span className="mt-1 block text-[11px] leading-4 text-[#718078]">{helper}</span>}<span className="mt-3 flex items-center gap-2"><input type="number" min={min} max={max} step={step} value={Number.isFinite(value) ? value : ""} placeholder={placeholder} onChange={(event) => onChange(event.currentTarget.value === "" ? Number.NaN : Number(event.currentTarget.value))} className="min-w-0 flex-1 border-b border-[#173D35]/25 bg-transparent px-0 py-1 font-serif text-xl font-bold text-[#173D35] outline-none transition placeholder:font-sans placeholder:text-sm placeholder:font-normal placeholder:text-[#9BA49E] focus:border-[#173D35]" />{suffix && <span className="shrink-0 text-xs font-semibold text-[#718078]">{suffix}</span>}</span></label>;
}

export function TextField({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="block"><span className="text-[11px] font-bold tracking-[0.08em] text-[#68756E]">{label}</span><input value={value} placeholder={placeholder} onChange={(event) => onChange(event.currentTarget.value)} className="mt-1.5 w-full border border-[#173D35]/15 bg-[#FCFBF7] px-3 py-2.5 text-sm outline-none transition focus:border-[#173D35]/50 focus:ring-2 focus:ring-[#173D35]/10" /></label>; }

export function TextAreaField({ label, value, onChange, placeholder, helper, rows = 3 }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; helper?: string; rows?: number }) { return <label className="block rounded-none border border-[#173D35]/10 bg-[#FCFBF7] p-3.5 transition focus-within:border-[#173D35]/45 focus-within:shadow-[0_0_0_3px_rgba(23,61,53,.08)]"><span className="block text-sm font-bold leading-5 text-[#27352E]">{label}</span>{helper && <span className="mt-1 block text-[11px] leading-4 text-[#718078]">{helper}</span>}<textarea rows={rows} value={value} placeholder={placeholder} onChange={(event) => onChange(event.currentTarget.value)} className="mt-3 w-full resize-y border border-[#173D35]/15 bg-white px-3 py-2.5 text-sm leading-6 text-[#27352E] outline-none transition placeholder:text-[#9BA49E] focus:border-[#173D35]/50 focus:ring-2 focus:ring-[#173D35]/10" /></label>; }

export function SelectField({ label, value, onChange, options, helper }: { label: string; value: string | number; onChange: (value: string) => void; options: { value: string | number; label: string }[]; helper?: string }) { return <label className="block rounded-none border border-[#173D35]/10 bg-[#FCFBF7] p-3.5 transition focus-within:border-[#173D35]/45 focus-within:shadow-[0_0_0_3px_rgba(23,61,53,.08)]"><span className="block text-sm font-bold leading-5 text-[#27352E]">{label}</span>{helper && <span className="mt-1 block text-[11px] leading-4 text-[#718078]">{helper}</span>}<select value={value} onChange={(event) => onChange(event.currentTarget.value)} className="mt-3 w-full border-b border-[#173D35]/25 bg-transparent px-0 py-1.5 text-sm font-semibold text-[#173D35] outline-none focus:border-[#173D35]">{options.map((option) => <option key={String(option.value)} value={option.value}>{option.label}</option>)}</select></label>; }

export function CheckField({ label, checked, onChange, detail }: { label: string; checked: boolean; onChange: (checked: boolean) => void; detail?: string }) { return <label className="group flex cursor-pointer gap-3 rounded-none border border-[#173D35]/10 bg-[#FCFBF7] p-3 text-sm transition hover:border-[#173D35]/25"><input className="peer sr-only" type="checkbox" checked={checked} onChange={(event) => onChange(event.currentTarget.checked)} /><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center border border-[#173D35]/35 bg-white text-transparent transition peer-checked:border-[#173D35] peer-checked:bg-[#173D35] peer-checked:text-white"><Check className="h-3.5 w-3.5 stroke-[3]" /></span><span className="leading-5"><strong className="font-semibold text-[#314039]">{label}</strong>{detail && <small className="mt-0.5 block text-[11px] leading-4 text-[#718078]">{detail}</small>}</span></label>; }

export function SectionCard({ code, title, description, children, tone = "green" }: { code: string; title: string; description?: string; children: ReactNode; tone?: "green" | "red" | "blue" }) {
  const color = { green: "#173D35", red: "#9A3E35", blue: "#273C73" }[tone];
  return <section className="relative overflow-hidden border border-[#173D35]/12 bg-white shadow-[0_10px_30px_rgba(28,45,35,.055)]"><div className="absolute bottom-0 left-0 top-0 w-1" style={{ backgroundColor: color }} /><div className="absolute -right-12 -top-16 h-40 w-40 rounded-full border opacity-10" style={{ borderColor: color }} /><div className="absolute -right-2 -top-6 h-24 w-24 rounded-full border opacity-10" style={{ borderColor: color }} /><div className="relative p-5 sm:p-6"><div className="mb-5 flex flex-col gap-2 border-b border-[#173D35]/10 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-[10px] font-bold tracking-[0.16em]" style={{ color }}>{code}</p><h2 className="mt-1 font-serif text-xl font-bold text-[#1F2D26]">{title}</h2></div>{description && <p className="max-w-xl text-xs leading-5 text-[#718078]">{description}</p>}</div>{children}</div></section>;
}

export function FieldSet({ title, description, children }: { title: string; description?: string; children: ReactNode }) { return <div><h3 className="border-l-2 pl-2 text-xs font-bold tracking-[0.08em] text-[#4D5E54]" style={{ borderColor: "currentColor" }}>{title}</h3>{description && <p className="mt-1.5 text-[11px] leading-4 text-[#718078]">{description}</p>}<div className="mt-2">{children}</div></div>; }
